[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/focal/indico-213
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/focal/redis-k8s-7
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/focal/redis-k8s-7
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  indico/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  indico/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  indico/0 [idle] waiting: Waiting for database availability
[32mINFO    [0m integration.new_relations.test_new_relations:test_new_relations.py:696 Verifying that the charm doesn't block when the extensions are enabled
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  database/0 [executing] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
  indico/0 [executing] waiting: Waiting for database availability
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [idle] active: 
  database/2 [idle] active: 
  indico/0 [idle] maintenance: Adding indico layer to pebble
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  02:44:39Z

App                      Version               Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application                            active       1  postgresql-test-app  latest/edge    254  10.152.183.28   no       received database credentials of the first database
another-data-integrator                        waiting      1  data-integrator      latest/stable   41  10.152.183.254  no       installing agent
another-database         14.13                 active       3  postgresql-k8s                        1  10.152.183.143  no       
data-integrator                                waiting      1  data-integrator      latest/stable   41  10.152.183.231  no       installing agent
database                 14.13                 active       3  postgresql-k8s                        0  10.152.183.123  no       
indico                   3.3.1                 active       1  indico               latest/stable  213  10.152.183.167  no       
other-discourse-k8s      3.3.0                 active       1  discourse-k8s        latest/stable  173  10.152.183.208  no       
postgresql-test-app                            active       2  postgresql-test-app  latest/edge    254  10.152.183.177  no       received database credentials of the first database
redis-broker             ubuntu/redis@691f315  active       1  redis-k8s            latest/stable    7                  no       
redis-cache              ubuntu/redis@691f315  active       1  redis-k8s            latest/stable    7                  no       
redis-k8s                7.2.5                 active       1  redis-k8s            latest/edge     36  10.152.183.92   no       

Unit                        Workload  Agent  Address     Ports     Message
another-application/0*      active    idle   10.1.53.22            received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.53.26            Please relate the data-integrator with the desired product
another-database/0*         active    idle   10.1.53.13            Primary
another-database/1          active    idle   10.1.53.15            
another-database/2          active    idle   10.1.53.14            
data-integrator/0*          blocked   idle   10.1.53.25            Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.53.19            Primary
database/1                  active    idle   10.1.53.24            
database/2                  active    idle   10.1.53.23            
indico/0*                   active    idle   10.1.53.34            
other-discourse-k8s/0*      active    idle   10.1.53.30            
postgresql-test-app/0*      active    idle   10.1.53.8             received database credentials of the first database
postgresql-test-app/1       active    idle   10.1.53.9             received database credentials of the first database
redis-broker/0*             active    idle   10.1.53.35  6379/TCP  
redis-cache/0*              active    idle   10.1.53.37  6379/TCP  
redis-k8s/0*                active    idle   10.1.53.29            

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-database-1: 02:18:19 ERROR unit.database/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/model.py", line 3213, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-database-1/secret-get', '--label', 'database-peers.database.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-1/charm/./src/charm.py", line 2202, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-1/charm/./src/charm.py", line 916, in _on_postgresql_pebble_ready
    self.unit.set_workload_version(self._patroni.rock_postgresql_version)
  File "/var/lib/juju/agents/unit-database-1/charm/./src/charm.py", line 1534, in _patroni
    self.get_secret(APP_SCOPE, USER_PASSWORD_KEY),
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-1/charm/./src/charm.py", line 350, in get_secret
    return self.peer_relation_data(scope).get_secret(peers.id, secret_key)
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 517, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2028, in get_secret
    and full_field not in self.current_secret_fields
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1985, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2316, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1119, in _get_group_secret_contents
    if (secret := self._get_relation_secret(relation.id, group)) and (
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 504, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2303, in _get_relation_secret
    return self.secrets.get(
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 808, in get
    if secret.meta:
  File "/var/lib/juju/agents/unit-database-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 638, in meta
    self._secret_meta = self._model.get_secret(label=self.label)
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/model.py", line 299, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/model.py", line 3579, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-database-1/charm/venv/ops/model.py", line 3215, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied

unit-database-1: 02:18:19 ERROR juju.worker.uniter.operation hook "postgresql-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-database-1: 02:18:19 ERROR juju.worker.uniter pebble poll failed for container "postgresql": failed to send pebble-ready event: hook failed
unit-database-0: 02:26:06 ERROR unit.database/0.juju-log Kubernetes service get failed: services "database" not found
unit-database-0: 02:26:06 ERROR unit.database/0.juju-log Kubernetes service patch failed: services "database" not found
unit-database-0: 02:26:27 ERROR unit.database/0.juju-log Kubernetes service get failed: services "database" not found
unit-database-0: 02:26:27 ERROR unit.database/0.juju-log Kubernetes service patch failed: services "database" not found
unit-database-0: 02:34:26 ERROR unit.database/0.juju-log database:21: Invalid extra user roles: test
unit-database-0: 02:34:26 ERROR unit.database/0.juju-log database:21: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 92, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 244, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 02:34:30 ERROR unit.database/0.juju-log database:20: Invalid extra user roles: test
unit-database-0: 02:34:30 ERROR unit.database/0.juju-log database:20: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 92, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 244, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
application-redis-cache: 02:43:02 ERROR unit.redis-cache/0.juju-log redis:31: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 159, in <module>
    main(RedisCharm)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/lib/charms/redis_k8s/v0/redis.py", line 91, in _on_relation_changed
    event.relation.data[self.model.unit]['hostname'] = str(self._bind_address(event))
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/lib/charms/redis_k8s/v0/redis.py", line 103, in _bind_address
    return self.app.name
AttributeError: 'RedisProvides' object has no attribute 'app'
application-redis-cache: 02:43:02 ERROR juju.worker.caasoperator.uniter.redis-cache/0.operation hook "redis-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...